# config.yaml
 
model:
name: resnet101       # Pretrained model name (e.g., resnet18, resnet50, etc.)
num_classes: 10       # Number of classes for your specific dataset

training:
batch_size: 32
num_epochs: 20
learning_rate: 0.001
optimizer: sgd       # Options: adam, sgd, etc.
momentum: 0.9         # Only for SGD optimizer
