model:
name: deeplabv3_resnet-101      # Pretrained model name
num_classes: 19       		# Number of classes for Cityscapes
 
training:
batch_size: 1
num_epochs: 80
learning_rate: 0.0005
optimizer: sgd       		# Options: adam, sgd, etc.
momentum: 0.9        		# Only for SGD optimizer
