model:
name: deeplabv3_resnet-101      # Pretrained model name
num_classes: 11       		# Number of classes for Cityscapes
 
training:
batch_size: 3
num_epochs: 80
learning_rate: 0.001
optimizer: sgd       		# Options: adam, sgd, etc.
momentum: 0.9        		# Only for SGD optimizer
